/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswingpractice;

import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.util.ArrayList;

/**
 *
 * @author zaberoy21
 */
public class LoginQmark extends javax.swing.JFrame
{
    private ArrayList<javax.swing.JPanel> panels = new ArrayList<javax.swing.JPanel>();
    
    public LoginQmark() //constructor
    {
        initComponents();
        
        int width = this.getContentPane().getWidth();
        int height = this.getContentPane().getHeight();
        StartScreen jp = new StartScreen();
        this.add(jp);
        panels.add(jp);
        
        loginScreen jp1 = new loginScreen();
        this.add(jp1);
        panels.add(jp1);
        
        mainScreen jp2 = new mainScreen();
        this.add(jp2);
        panels.add(jp2);
             
        jp.setLocation(0,0);
        jp.setSize(width, height);
        
        jp1.setLocation(0,0);
        jp1.setSize(width,height);
        
        jp2.setLocation(0,0);
        jp2.setSize(width, height);
        
        this.pack();
        this.showPanel(0); 
        
        
                
    }
    
    public void showPanel(int panelNum)
    {
        for (int i = 0; i < this.panels.size(); i++)
        {
            panels.get(i).setVisible(false);
        }
        panels.get(panelNum).setVisible(true);
    }
    
/**
    public void initListeners() {
        addComponentListener(new ComponentListener() {

            @Override
            public void componentResized(ComponentEvent e) {        
                panels.get(0).updatePanelSize();
            }

            @Override
            public void componentHidden(ComponentEvent evt) {}

            @Override
            public void componentShown(ComponentEvent evt) {}

            @Override
            public void componentMoved(ComponentEvent evt) {}
        });
    }
/**

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
